### ISSUE TITLE
install / upgrade of php-redis does not restart php-fpm

### ISSUE THREAD

**Issue by kubicgruenfeld** [oerdnj/deb.sury.org#1306]
**Unsupported distributions**
 - [x] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [x] I'm *not* trying to mirror the repositories using wget, curl, mozilla. If I am mirroring the packages.sury.org repository, I am properly using [rsync](https://www.patreon.com/posts/use-rsync-luke-32563640) to minimize the traffic.

Hey Ondřej, i might have found a bug in the php-redis packages.
Since a few weeks we have issues with php-fpm after upgrades of php-redis. For example we have logentries like this:

```
Error #2 session_start(): Cannot find save handler 'redis' - session startup failed
```
After a restart of php-fpm everything works just fine.

**To Reproduce**
1. apt purge php-redis
2. restart php-fpm
3. install php-redis
4. try to use php-redis through fpm.

**Expected behavior**
php-fpm is reloaded after upgrade/installation of php-redis

**Distribution (please complete the following information):**
 - OS: Ubuntu 1604, 18.04
 - Architecture: amd64
 - Repository: https://launchpad.net/~ondrej/+archive/ubuntu/php

**Package(s) (please complete the following information):**
```
# apt-cache policy php-redis
php-redis:
  Installed: 5.1.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1
  Candidate: 5.1.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1
  Version table:
 *** 5.1.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     3.1.6-1build1 500
        500 https://mirror.syseleven.de/weekly/ubuntu bionic/universe amd64 Packages
```

**Additional context**
I looked into the package control files and compared php-redis with php7.2-mysql, for mysql i found this file *control/triggers* with content:

```
activate-noawait /etc/php/7.2/apache2/conf.d
activate-noawait /etc/php/7.2/apache2filter/conf.d
activate-noawait /etc/php/7.2/fpm/conf.d
```

For php-redis i could not found this trigger file. So there is also not a line like this:
```
Processing triggers for php7.2-fpm (7.2.26-1+ubuntu18.04.1+deb.sury.org+1) ...
```
after the installation of php-redis.

I would be happy to provide further information if needed.

Thanks for your help!

**Comment by Cieper** [comment]
Can confirm, I had the same happen:

Distribution (please complete the following information):

* OS: Debian 9.11 (Stretch)
* Architecture: amd64
* Repository: https://packages.sury.org/php/ stretch main

**Comment by hensema** [comment]
IMHO the best solution would be to properly create version-specific packages for php-redis (php7.1-redis, php7.2-redis, etc).

Now php-redis is a weird exception: it's a package containing the module for all php versions.

**Comment by lamaral** [comment]
I have encountered the same problem twice already when upgrading php7.3-fpm and php-redis together. 

**Distribution (please complete the following information):**
- OS: Debian 9.11 (Stretch)
- Architecture: amd64
- Repository: https://packages.sury.org/php/ stretch main

When looking at phpinfo() output from php-fpm, redis wasn't shown at all in there. After restarting FPM, redis would show up again. 

I did some investigation and noticed operations happening in the following order:
php7.3-fpm preinst/prerm runs (Preparing to unpack)
php7.3-fpm gets unpacked (Unpacking)
php-redis preinst/prerm runs (Preparing to unpack)
php-redis gets unpacked (Unpacking)
php7.3-fpm gets setup (Setting up php7.3-fpm)
php-redis gets setup (Setting up php-redis)

Looking at the Debian files, php-redis on it's prerm/preinst runs phpdismod and disables itself, removing the `/etc/php/7.3/fpm/conf.d/20-redis.ini` symlink. 
Then php7.3-fpm on it's postinst does a invoke-rc.d that restarts itself. 
And last, php-redis runs phpenmod and re-enables itself, after php7.3-fpm has already restarted.

If I get some time tomorrow, I will try to build a custom Debian package for php-redis with the triggers file to see if the problem is solved.

**Comment by oerdnj** [comment]
Thanks, this contains useful debugging info.

**Comment by sts** [comment]
It looks like this bug is also related: https://github.com/oerdnj/deb.sury.org/issues/1306

**Comment by sts** [comment]
The `postinst` scripts of pecl extensions are calling `enmod` of  `/usr/lib/php/php-maintscript-helper`:

```
if [ -e /usr/lib/php/php-maintscript-helper ] ; then
    . /usr/lib/php/php-maintscript-helper

    for version in 7.3 7.2 7.1 7.0 5.6 ; do
        for name in redis; do
            php_invoke enmod "$version" ALL "$name" || exit $?
    done
```

When looking at `/usr/lib/php/php-maintscript-helper`, `dpkg-trigger` would get activated after `enmod` when `$PHP_NEED_ACTION` AND `$rcd_action` contain non-empty strings:

```bash
         if [ -n "${PHP_NEED_ACTION:-}" -a -n "$rcd_action" ]; then
             dpkg-trigger /etc/php/$version/$sapi/conf.d
         fi
```

When adding `set -x` to `php-maintscript-helper` I see the following at the `$PHP_NEED_ACTION` and `$rcd_action`:

```
+ '[' -n 1 -a -n '' ']'
```

I also don't see where `$rcd_action` should be set as its a local to `php_invoke()` and its not evaluated. It makes the impression `$rcd_action` is leftover from (maybe) refactoring `apache2-maintscript-helper` for php-fpm?

Side note: `dpkg-trigger` is also not activated in the supplied `/usr/sbin/phpenmod` and `/usr/sbin/phpenmod` commands; not sure what the expected behaviour is here.

**Comment by oerdnj** [comment]
!!! That has been very helpful.  I've just uploaded a new version of `php-defaults` which might fix the issue.

(There's already working build in ppa:ondrej/php-qa.)

**Comment by oerdnj** [comment]
Old version:
```
# apt-get install php-redis
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  php-igbinary
Suggested packages:
  redis-server
The following NEW packages will be installed:
  php-igbinary php-redis
0 upgraded, 2 newly installed, 0 to remove and 90 not upgraded.
Need to get 625 kB of archives.
After this operation, 4665 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php-igbinary amd64 3.1.0+2.0.8-2+ubuntu18.04.1+deb.sury.org+1 [194 kB]
Get:2 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php-redis amd64 5.1.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1 [431 kB]
Fetched 625 kB in 0s (1347 kB/s)
Selecting previously unselected package php-igbinary.
(Reading database ... 18061 files and directories currently installed.)
Preparing to unpack .../php-igbinary_3.1.0+2.0.8-2+ubuntu18.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php-igbinary (3.1.0+2.0.8-2+ubuntu18.04.1+deb.sury.org+1) ...
Selecting previously unselected package php-redis.
Preparing to unpack .../php-redis_5.1.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php-redis (5.1.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1) ...
Setting up php-igbinary (3.1.0+2.0.8-2+ubuntu18.04.1+deb.sury.org+1) ...
Setting up php-redis (5.1.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1) ...
```

New version:
```
# apt-get install php-redis
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libicu60
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  php-igbinary
Suggested packages:
  redis-server
The following NEW packages will be installed:
  php-igbinary php-redis
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/625 kB of archives.
After this operation, 4665 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Selecting previously unselected package php-igbinary.
(Reading database ... 18109 files and directories currently installed.)
Preparing to unpack .../php-igbinary_3.1.0+2.0.8-2+ubuntu18.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php-igbinary (3.1.0+2.0.8-2+ubuntu18.04.1+deb.sury.org+1) ...
Selecting previously unselected package php-redis.
Preparing to unpack .../php-redis_5.1.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1_amd64.deb ...
Unpacking php-redis (5.1.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1) ...
Setting up php-igbinary (3.1.0+2.0.8-2+ubuntu18.04.1+deb.sury.org+1) ...
Setting up php-redis (5.1.1+4.3.0-1+ubuntu18.04.1+deb.sury.org+1) ...
Processing triggers for php7.4-fpm (7.4.1-1+ubuntu18.04.1+deb.sury.org+1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Processing triggers for php7.4-cli (7.4.1-1+ubuntu18.04.1+deb.sury.org+1) ...
```

**Comment by sts** [comment]
@oerdnj php-defaults? you mean php-common? can you send a link to the deb file, I would test it on our end.

```
dpkg -S /usr/lib/php/php-maintscript-helper
php-common: /usr/lib/php/php-maintscript-helper
```

**Comment by oerdnj** [comment]
That's the binary package, the source package is named `php-defaults` :)

**Comment by oerdnj** [comment]
I am thinking in source packages...

**Comment by oerdnj** [comment]
Anyway, I believe this issue has been fixed now. Please reopen the issue (or open a new one) if you encounter the same problem with `php-common >= 72~`.

**Comment by sts** [comment]
@oerdnj happens with php 7.3 as well

**Comment by oerdnj** [comment]
php-common is a version agnostic. It should be already fixed. Thanks for the debugging!

**Comment by ttk** [comment]
I confirmed that the triggers now run after the package install/upgrade.  However, they still don't run after an apt remove.  Comparing the removal of two different packages:

```
root@ubuntu-bionic:~# apt remove php7.3-zip
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libdumbnet1 libicu60 libzip4
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  php7.3-zip
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 94.2 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 96031 files and directories currently installed.)
Removing php7.3-zip (7.3.14-1+ubuntu18.04.1+deb.sury.org+1) ...
Processing triggers for php7.3-fpm (7.3.14-1+ubuntu18.04.1+deb.sury.org+1) ...
```

```
root@ubuntu-bionic:~# apt remove php-memcache
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libdumbnet1 libicu60 libzip4
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  php-memcache
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 700 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 96040 files and directories currently installed.)
Removing php-memcache (3.0.9~20170802.e702b5f-3+ubuntu18.04.1+deb.sury.org+20191129) ...
```

Not sure if the missing trigger on removal would cause any problems, but I just wanted to point this out.

**Comment by oerdnj** [comment]
> Not sure if the missing trigger on removal would cause any problems, but I just wanted to point this out.

Thanks, @ttk, that's a good point.
