### ISSUE TITLE
nginx packages "kept back", `mod-brotli` and `mod-ssl-ct` will be removed

### ISSUE THREAD

**Issue by fmonts** [oerdnj/deb.sury.org#2089]
I have this situation on all my Ubuntu 20 and 22 machines with nginx-mainline repository. 

`apt upgrade` says:
> The following packages have been kept back:
  libnginx-mod-http-geoip libnginx-mod-http-image-filter libnginx-mod-http-xslt-filter libnginx-mod-mail libnginx-mod-stream libnginx-mod-stream-geoip nginx-common nginx-core

If I do a `dist-upgrade`, I get:

> The following packages will be REMOVED:
>   libnginx-mod-brotli libnginx-mod-ssl-ct
> The following NEW packages will be installed:
>   nginx
> The following packages will be upgraded:
>   libnginx-mod-http-geoip libnginx-mod-http-image-filter libnginx-mod-http-xslt-filter libnginx-mod-mail libnginx-mod-stream libnginx-mod-stream-geoip nginx-common nginx-core

Are those packages deprecated and meant to be removed? I don't find any information about this.

This is what I have installed:

> $ apt list --installed | grep nginx
> libnginx-mod-brotli/now 1.25.3-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-1+ubuntu20.04.1+deb.sury.org+1]
> libnginx-mod-http-geoip/now 1.25.3-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu20.04.1+deb.sury.org+1]
> libnginx-mod-http-image-filter/now 1.25.3-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu20.04.1+deb.sury.org+1]
> libnginx-mod-http-xslt-filter/now 1.25.3-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu20.04.1+deb.sury.org+1]
> libnginx-mod-mail/now 1.25.3-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu20.04.1+deb.sury.org+1]
> libnginx-mod-ssl-ct/now 1.25.3-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-1+ubuntu20.04.1+deb.sury.org+1]
> libnginx-mod-stream-geoip/now 1.25.3-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu20.04.1+deb.sury.org+1]
> libnginx-mod-stream/now 1.25.3-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu20.04.1+deb.sury.org+1]
> nginx-common/now 1.25.3-1+ubuntu20.04.1+deb.sury.org+1 all [installed,upgradable to: 1.25.4-2+ubuntu20.04.1+deb.sury.org+1]
> nginx-core/now 1.25.3-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu20.04.1+deb.sury.org+1]

and on another server:

> libnginx-mod-brotli/jammy,now 1.25.4-1+ubuntu22.04.1+deb.sury.org+1 amd64 [installed,automatic]
> libnginx-mod-http-geoip/now 1.25.4-1+ubuntu22.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu22.04.1+deb.sury.org+1]
> libnginx-mod-http-image-filter/now 1.25.4-1+ubuntu22.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu22.04.1+deb.sury.org+1]
> libnginx-mod-http-xslt-filter/now 1.25.4-1+ubuntu22.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu22.04.1+deb.sury.org+1]
> libnginx-mod-mail/now 1.25.4-1+ubuntu22.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu22.04.1+deb.sury.org+1]
> libnginx-mod-ssl-ct/jammy,now 1.25.4-1+ubuntu22.04.1+deb.sury.org+1 amd64 [installed,automatic]
> libnginx-mod-stream-geoip/now 1.25.4-1+ubuntu22.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu22.04.1+deb.sury.org+1]
> libnginx-mod-stream/now 1.25.4-1+ubuntu22.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu22.04.1+deb.sury.org+1]
> nginx-common/jammy,now 1.25.4-1+ubuntu22.04.1+deb.sury.org+1 all [installed,upgradable to: 1.25.4-2+ubuntu22.04.1+deb.sury.org+1]
> nginx-core/now 1.25.4-1+ubuntu22.04.1+deb.sury.org+1 amd64 [installed,upgradable to: 1.25.4-2+ubuntu22.04.1+deb.sury.org+1]

It looks like for ssl-ct and brotli there isn't a -2 version

**Comment by tvvpm** [comment]
We are on the same situation:

> root@web02:~# apt dist-upgrade
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Calculating upgrade... Done
> The following packages will be REMOVED:
>   libnginx-mod-brotli libnginx-mod-ssl-ct
> The following packages will be upgraded:
>   debsuryorg-archive-keyring libnginx-mod-http-geoip libnginx-mod-http-image-filter libnginx-mod-http-xslt-filter
>   libnginx-mod-mail libnginx-mod-stream libnginx-mod-stream-geoip nginx nginx-common nginx-core
> 10 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.

After upgrade NGINX stops working.

**Comment by brettt89** [comment]
We are also being impacted by this on Ubuntu 22.04.

It appears as though this version of `libnginx-mod-ssl-ct` has had changes to its `postrm` file in which the expected filename changed from `50-mod-ssl-ct.conf` to `70-mod-ssl-ct.conf` resulting in the symlink not being renamed when removed/purged.

This appears to only impacts upgrading from previous installation to newest, rather than fresh installation.

**Comment by tvvpm** [comment]
> This appears to only impacts upgrading from previous installation to newest, rather than fresh installation.

In my case (debian 12.5) removing all NGINX packages and install them again does not work.

**Comment by ghbob** [comment]
Disclaimer: I am out of my depth here, take everything with a grain of salt :)

Concerning brotli, it has been replaced with a different package (at least for Jammy), see: https://github.com/oerdnj/deb.sury.org/issues/2086#issuecomment-1965437706

Most likely related as well: https://github.com/oerdnj/deb.sury.org/issues/2073

### Server 1: broken nginx after apt full-upgrade (Ubuntu 22 / Jammy)
I had a similar issue yesterday when running `apt full-upgrade` on a Ubuntu 22 (my Ubuntu 20 setups didn't seem to have the same issue), that broke my Nginx setup (with `ppa:ondrej/nginx-mainline`).


The full-upgrade removed the old brotli package:
`Removing libnginx-mod-brotli (1.25.3-1+ubuntu22.04.1+deb.sury.org+2) ...`

which lead to

`nginx[348999]: [emerg] 348999#348999: unknown directive "brotli" in /etc/nginx/some.conf:30`

and the whole upgrade failing (I think).

What I did to fix it was to
1. disable the brotli configuration
2. installing: `nginx-extras` as well as the new package for brotli: `libnginx-mod-http-brotli-filter` and
3. running `apt-get install --fix-broken` to repair the failed upgrade.
4. Afterwards I could re-enabled the brotli configuration again.

Maybe installing the new bortli package beforehand would have helped, I don't know.

### Server 2: no longer required packages on apt full-upgrade (Ubuntu 22 / Jammy)
Another Ubuntu 22 setup, without `libnginx-mod-brotli` installed though, currently looks like this before the upgrade:

```
apt full-upgrade
...
The following packages were automatically installed and are no longer required:
  geoip-database libgeoip1 libnginx-mod-http-geoip libnginx-mod-http-image-filter libnginx-mod-http-xslt-filter libnginx-mod-mail libnginx-mod-stream libnginx-mod-stream-geoip nginx-core
...
The following packages have been kept back:
  libgpgme11
The following packages will be upgraded:
  cloud-init libbrotli1 php8.2-cli php8.2-common php8.2-fpm php8.2-gd php8.2-intl php8.2-mbstring php8.2-mysql php8.2-opcache php8.2-readline php8.2-xml
12 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

The "no longer required" packages make me somewhat nervous, could someone with more knowledge explain what's going on here?

I think it's because `nginx-core` is to be removed because all of these flavours (light, core, full) are just `nginx` now?
The other to-be-removed dependencies were just dependencies of `nginx-core` but not `nginx` (according to `apt show`)?


### What's currently the right way to run this upgrade on Ubuntu 22?

My best guess right now: install `nginx-extras` and `libnginx-mod-http-brotli-filter` (which itself is not part of nginx-extras?) before hand to keep the dependencies and not break brotli if it's configured somewhere?

Thanks!

**Comment by oerdnj** [comment]
This was triggered by https://github.com/oerdnj/deb.sury.org/issues/2073

I will chase the remaining bugs soon as the time allows.

Generally speaking, you don’t need nginx-extra, you need to install modules that you are actually using

**Comment by ziming** [comment]
@ghbob I install just `libnginx-mod-brotli` and then run `apt-get install --fix-broken`

it didn't work, guess i will try install `nginx-extras` later

**Comment by oerdnj** [comment]
This should be resolved in:

```
# apt-cache policy libnginx-mod-brotli libnginx-mod-ssl-ct
libnginx-mod-brotli:
  Installed: 1:1.0.0~rc+1.24.0-5+ubuntu22.04.1+deb.sury.org+4
  Candidate: 1:1.0.0~rc+1.24.0-5+ubuntu22.04.1+deb.sury.org+4
  Version table:
 *** 1:1.0.0~rc+1.24.0-5+ubuntu22.04.1+deb.sury.org+4 500
        500 https://ppa.launchpadcontent.net/ondrej/nginx/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
libnginx-mod-ssl-ct:
  Installed: 1:1.3.2+1.24.0-2+ubuntu22.04.1+deb.sury.org+1
  Candidate: 1:1.3.2+1.24.0-2+ubuntu22.04.1+deb.sury.org+1
  Version table:
 *** 1:1.3.2+1.24.0-2+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/nginx/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

If there are further problems, please open new issue with current description.

**Comment by fmonts** [comment]
This made it worse, a simple `apt update && apt upgrade` caused me huge downtime because nginx failed to update:

> dpkg: error processing package nginx (--configure):
>  installed nginx package post-installation script subprocess returned error exit status 1
> dpkg: dependency problems prevent configuration of libnginx-mod-http-image-filter:
>  libnginx-mod-http-image-filter depends on nginx-abi-1.24.0-1; however:
>   Package nginx-abi-1.24.0-1 is not installed.
>   Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> 
> dpkg: error processing package libnginx-mod-http-image-filter (--configure):
>  dependency problems - leaving unconfigured
> dpkg: dependency problems prevent configuration of libnginx-mod-stream:
>  libnginx-mod-stream depends on nginx-abi-1.24.0-1; however:
>   Package nginx-abi-1.24.0-1 is not installed.
>   Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> 
> dpkg: error processing package libnginx-mod-stream (--configure):
>  dependency problems - leaving unconfigured
> dpkg: dependency problems prevent configuration of libnginx-mod-ssl-ct:
>  libnginx-mod-ssl-ct depends on nginx-abi-1.24.0-1; however:
>   Package nginx-abi-1.24.0-1 is not installed.
>   Package nginx which provNo apport report written because the error message indicates its a followup error from a previous failure.
>                                                                                                                                     No apport report written because the error message indicates its a followup error from a previous failure.
>  No apport report written because MaxReports is reached already
>                                                                No apport report written because MaxReports is reached already
>                                                                                                                              No apport report written because MaxReports is reached already
>                                                                                                                                                                                            No apport report written because MaxReports is reached already
>             ides nginx-abi-1.24.0-1 is not configured yet.
> 
> dpkg: error processing package libnginx-mod-ssl-ct (--configure):
>  dependency problems - leaving unconfigured
> dpkg: dependency problems prevent configuration of nginx-common:
>  nginx-common depends on nginx (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
>   Package nginx is not configured yet.
>  nginx-common depends on nginx (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
>   Package nginx is not configured yet.
> 
> dpkg: error processing package nginx-common (--configure):
>  dependency problems - leaving unconfigured
> dpkg: dependency problems prevent configuration of libnginx-mod-stream-geoip:
>  libnginx-mod-stream-geoip depends on nginx-abi-1.24.0-1; however:
>   Package nginx-abi-1.24.0-1 is not installed.
>   Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
>  libnginx-mod-stream-geoip depends on libnginx-mod-stream (= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
>   Package libnginx-mod-stream is not configured yet.
> 
> dpkg: error processing package libnginx-mod-stream-geoip (--configure):
>  dependency problems - leaving unconfigured
> dpkg: dependency problems prevent configuration of libnginx-mod-http-xslt-filter:
>  libnginx-mod-http-xslt-filter depends on nginx-abi-1.24.0-1; however:
>   Package nginx-abi-1.24.0-1 is not installed.
>   Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> 
> dpkg: error processing package libnginx-mod-http-xslt-filter (--configure):
>  dependency problems - leaving unconfigured
> Setting up linux-image-5.15.0-101-generic (5.15.0-101.111) ...
> I: /boot/vmlinuz.old is now a symlink to vmlinuz-5.15.0-100-generic
> I: /boot/initrd.img.old is now a symlink to initrd.img-5.15.0-100-generic
> I: /boot/vmlinuz is now a symlink to vmlinuz-5.15.0-101-generic
> I: /boot/initrd.img is now a symlink to initrd.img-5.15.0-101-generic
> dpkg: dependency problems prevent configuration of libnginx-mod-http-geoip:
>  libnginx-mod-http-geoip depends on nginx-abi-1.24.0-1; however:
>   Package nginx-abi-1.24.0-1 is not installed.
>   Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> 
> dpkg: error processing package libnginx-mod-http-geoip (--configure):
>  dependency problems - leaving unconfigured
> No apport report written because MaxReports is reached already
>                                                               dpkg: dependency problems prevent configuration of libnginx-mod-http-brotli-filter:
>  libnginx-mod-http-brotli-filter depends on nginx-abi-1.24.0-1; however:
>   Package nginx-abi-1.24.0-1 is not installed.
>   Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> 
> dpkg: error processing package libnginx-mod-http-brotli-filter (--configure):
>  dependency problems - leaving unconfigured
> No apport report written because MaxReports is reached already
>                                                               dpkg: dependency problems prevent configuration of libnginx-mod-brotli:
>  libnginx-mod-brotli depends on libnginx-mod-http-brotli-filter; however:
>   Package libnginx-mod-http-brotli-filter is not configured yet.
> 
> dpkg: error processing package libnginx-mod-brotli (--configure):
>  dependency problems - leaving unconfigured
> No apport report written because MaxReports is reached already
>                                                               dpkg: dependency problems prevent configuration of nginx-core:
>  nginx-core depends on libnginx-mod-http-geoip (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
>   Package libnginx-mod-http-geoip is not configured yet.
>  nginx-core depends on libnginx-mod-http-geoip (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
>   Package libnginx-mod-http-geoip is not configured yet.
>  nginx-core depends on libnginx-mod-http-image-filter (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
>   Package libnginx-mod-http-image-filter is not configured yet.
>  nginx-core depends on libnginx-mod-http-image-filter (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
>   Package libnginx-mod-http-image-filter is not configured yet.
>  nginx-core depends on libnginx-mod-http-xslt-filter (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
>   Package libnginx-mod-http-xslt-filter is not configured yet.
>  nginx-core depends on libnginx-mod-http-xslt-filter (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
>  No apport report written because MaxReports is reached already
>                                                                 Package libnginx-mod-http-xslt-filter is not configured yet.
>  nginx-core depends on libnginx-mod-stream (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
>   Package libnginx-mod-stream is not configured yet.
>  nginx-core depends on libnginx-mod-stream (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
>   Package libnginx-mod-stream is not configured yet.
>  nginx-core depends on libnginx-mod-stream-geoip (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
>   Package libnginx-mod-stream-geoip is not configured yet.
>  nginx-core depends on libnginx-mod-stream-geoip (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
>   Package libnginx-mod-stream-geoip is not configured yet.
>  nginx-core depends on nginx (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
>   Package nginx is not configured yet.
>  nginx-core depends on nginx (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
>   Package nginx is not configured yet.
> 
> dpkg: error processing package nginx-core (--configure):
>  dependency problems - leaving unconfigured
> dpkg: dependency problems prevent configuration of libnginx-mod-mail:
>  libnginx-mod-mail depends on nginx-abi-1.24.0-1; however:
>   Package nginx-abi-1.24.0-1 is not installed.
>   Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> 
> dpkg: error processing package libnginx-mod-mail (--configure):
>  dependency problems - leaving unconfigured
> No apport report written because MaxReports is reached already
>                                                               dpkg: dependency problems prevent configuration of libnginx-mod-http-brotli-static:
>  libnginx-mod-http-brotli-static depends on nginx-abi-1.24.0-1; however:
>   Package nginx-abi-1.24.0-1 is not installed.
>   Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> 
> dpkg: error processing package libnginx-mod-http-brotli-static (--configure):
>  dependency problems - leaving unconfigured
> No apport report written because MaxReports is reached already
>                                                               Setting up linux-modules-extra-5.15.0-101-generic (5.15.0-101.111) ...
> Setting up linux-modules-5.15.0-101-generic (5.15.0-101.111) ...
> Setting up linux-image-generic (5.15.0.101.98) ...
> Setting up linux-generic (5.15.0.101.98) ...
> Processing triggers for libc-bin (2.35-0ubuntu3.6) ...
> Processing triggers for ufw (0.36.1-4ubuntu0.1) ...
> Processing triggers for man-db (2.10.2-1) ...
> Processing triggers for php8.3-cli (8.3.4-1+ubuntu22.04.1+deb.sury.org+1) ...
> Processing triggers for php8.3-fpm (8.3.4-1+ubuntu22.04.1+deb.sury.org+1) ...
> Processing triggers for linux-image-5.15.0-101-generic (5.15.0-101.111) ...
> /etc/kernel/postinst.d/initramfs-tools:
> update-initramfs: Generating /boot/initrd.img-5.15.0-101-generic
> I: The initramfs will attempt to resume from /dev/nvme1n1p3
> I: (UUID=1551ae32-6c68-4425-ae6f-32e60dbb2404)
> I: Set the RESUME variable to override this.
> /etc/kernel/postinst.d/zz-update-grub:
> Sourcing file `/etc/default/grub'
> Sourcing file `/etc/default/grub.d/init-select.cfg'
> Generating grub configuration file ...
> Found linux image: /boot/vmlinuz-5.15.0-101-generic
> Found initrd image: /boot/initrd.img-5.15.0-101-generic
> Found linux image: /boot/vmlinuz-5.15.0-100-generic
> Found initrd image: /boot/initrd.img-5.15.0-100-generic
> Found linux image: /boot/vmlinuz-5.15.0-78-generic
> Found initrd image: /boot/initrd.img-5.15.0-78-generic
> Warning: os-prober will not be executed to detect other bootable partitions.
> Systems on them will not be added to the GRUB boot configuration.
> Check GRUB_DISABLE_OS_PROBER documentation entry.
> Adding boot menu entry for UEFI Firmware Settings ...
> done
> Errors were encountered while processing:
>  nginx
>  libnginx-mod-http-image-filter
>  libnginx-mod-stream
>  libnginx-mod-ssl-ct
>  nginx-common
>  libnginx-mod-stream-geoip
>  libnginx-mod-http-xslt-filter
>  libnginx-mod-http-geoip
>  libnginx-mod-http-brotli-filter
>  libnginx-mod-brotli
>  nginx-core
>  libnginx-mod-mail
>  libnginx-mod-http-brotli-static
> needrestart is being skipped since dpkg has failed
> E: Sub-process /usr/bin/dpkg returned an error code (1)
>

**Comment by DaveSophoServices** [comment]
I had to disable the nginx modules by removing everything (created a tar file then removed the symlinks) `tar -zcvf modules-enabled.tgz modules-enabled/` in modules-enabled (I guess I wasn't using any of them anyway) and then running 
`apt --fix-broken install`

**Comment by MrMarci666** [comment]
This seems to be still an issue, I have brotli enabled on a server, ran the usual update command `sudo apt update -y && sudo apt upgrade -y` and then I faced the same issues as @ghbob 's Server 1.

> Server 1: broken nginx after apt full-upgrade (Ubuntu 22 / Jammy)

The solution he described fixed the issue for me too, so thanks for that!

**Comment by michaelk83** [comment]
I was able to successfully upgrade `nginx` on Ubuntu 20.04 recently, but have also ran into the "packages are no longer required" situation:
```
sudo apt-get -s autoremove
...
The following packages will be REMOVED:
  libnginx-mod-http-geoip libnginx-mod-http-image-filter libnginx-mod-http-xslt-filter libnginx-mod-mail libnginx-mod-ssl-ct libnginx-mod-stream libnginx-mod-stream-geoip nginx-core
```

I've fixed most of these by marking `nginx-core` as manually installed, but this still leaves `libnginx-mod-ssl-ct` as auto-removable.  Is it no longer needed? AFAICT, it's not required by any of the nginx packages.

Here's what I have installed, currently:
```
libnginx-mod-brotli 1:1.0.0~rc+1.24.0-8+ubuntu20.04.1+deb.sury.org+1.24.0~1 all
libnginx-mod-http-brotli-filter 1:1.0.0~rc+1.24.0-8+ubuntu20.04.1+deb.sury.org+1.24.0~1 amd64
libnginx-mod-http-brotli-static 1:1.0.0~rc+1.24.0-8+ubuntu20.04.1+deb.sury.org+1.24.0~1 amd64
libnginx-mod-http-geoip 1.24.0-4+ubuntu20.04.1+deb.sury.org+1 amd64
libnginx-mod-http-image-filter 1.24.0-4+ubuntu20.04.1+deb.sury.org+1 amd64
libnginx-mod-http-xslt-filter 1.24.0-4+ubuntu20.04.1+deb.sury.org+1 amd64
libnginx-mod-mail 1.24.0-4+ubuntu20.04.1+deb.sury.org+1 amd64
libnginx-mod-ssl-ct 1:1.3.2+1.24.0-2+ubuntu20.04.1+deb.sury.org+1 amd64
libnginx-mod-stream 1.24.0-4+ubuntu20.04.1+deb.sury.org+1 amd64
libnginx-mod-stream-geoip 1.24.0-4+ubuntu20.04.1+deb.sury.org+1 amd64
nginx 1.24.0-4+ubuntu20.04.1+deb.sury.org+1 amd64
nginx-common 1.24.0-4+ubuntu20.04.1+deb.sury.org+1 all
nginx-core 1.24.0-4+ubuntu20.04.1+deb.sury.org+1 all
```
I upgraded from `1.24.0-1+ubuntu20.04.1+deb.sury.org+1`.

**Comment by fmonts** [comment]
Every time I upgrade I'm scared of downtime... 

I just tried an upgrade on 20.04 and I still got:

> May 20 05:33:24 web09 nginx[2038465]: 2024/05/20 05:33:24 [emerg] 2038465#2038465: module "/usr/share/nginx/modules/ngx_http_geoip_module.so" version 1025004 instea
> d of 1025005 in /etc/nginx/modules-enabled/50-mod-http-geoip.conf:1

with `apt --fix-broken install` not working as well.

Imho this repository should be delisted, for everyone's safety...

**Comment by apertureless** [comment]
> This made it worse, a simple `apt update && apt upgrade` caused me huge downtime because nginx failed to update:
> 
> > dpkg: error processing package nginx (--configure):
> > installed nginx package post-installation script subprocess returned error exit status 1
> > dpkg: dependency problems prevent configuration of libnginx-mod-http-image-filter:
> > libnginx-mod-http-image-filter depends on nginx-abi-1.24.0-1; however:
> > Package nginx-abi-1.24.0-1 is not installed.
> > Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> > dpkg: error processing package libnginx-mod-http-image-filter (--configure):
> > dependency problems - leaving unconfigured
> > dpkg: dependency problems prevent configuration of libnginx-mod-stream:
> > libnginx-mod-stream depends on nginx-abi-1.24.0-1; however:
> > Package nginx-abi-1.24.0-1 is not installed.
> > Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> > dpkg: error processing package libnginx-mod-stream (--configure):
> > dependency problems - leaving unconfigured
> > dpkg: dependency problems prevent configuration of libnginx-mod-ssl-ct:
> > libnginx-mod-ssl-ct depends on nginx-abi-1.24.0-1; however:
> > Package nginx-abi-1.24.0-1 is not installed.
> > Package nginx which provNo apport report written because the error message indicates its a followup error from a previous failure.
> > No apport report written because the error message indicates its a followup error from a previous failure.
> > No apport report written because MaxReports is reached already
> > No apport report written because MaxReports is reached already
> > No apport report written because MaxReports is reached already
> > No apport report written because MaxReports is reached already
> > ides nginx-abi-1.24.0-1 is not configured yet.
> > dpkg: error processing package libnginx-mod-ssl-ct (--configure):
> > dependency problems - leaving unconfigured
> > dpkg: dependency problems prevent configuration of nginx-common:
> > nginx-common depends on nginx (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
> > Package nginx is not configured yet.
> > nginx-common depends on nginx (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
> > Package nginx is not configured yet.
> > dpkg: error processing package nginx-common (--configure):
> > dependency problems - leaving unconfigured
> > dpkg: dependency problems prevent configuration of libnginx-mod-stream-geoip:
> > libnginx-mod-stream-geoip depends on nginx-abi-1.24.0-1; however:
> > Package nginx-abi-1.24.0-1 is not installed.
> > Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> > libnginx-mod-stream-geoip depends on libnginx-mod-stream (= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
> > Package libnginx-mod-stream is not configured yet.
> > dpkg: error processing package libnginx-mod-stream-geoip (--configure):
> > dependency problems - leaving unconfigured
> > dpkg: dependency problems prevent configuration of libnginx-mod-http-xslt-filter:
> > libnginx-mod-http-xslt-filter depends on nginx-abi-1.24.0-1; however:
> > Package nginx-abi-1.24.0-1 is not installed.
> > Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> > dpkg: error processing package libnginx-mod-http-xslt-filter (--configure):
> > dependency problems - leaving unconfigured
> > Setting up linux-image-5.15.0-101-generic (5.15.0-101.111) ...
> > I: /boot/vmlinuz.old is now a symlink to vmlinuz-5.15.0-100-generic
> > I: /boot/initrd.img.old is now a symlink to initrd.img-5.15.0-100-generic
> > I: /boot/vmlinuz is now a symlink to vmlinuz-5.15.0-101-generic
> > I: /boot/initrd.img is now a symlink to initrd.img-5.15.0-101-generic
> > dpkg: dependency problems prevent configuration of libnginx-mod-http-geoip:
> > libnginx-mod-http-geoip depends on nginx-abi-1.24.0-1; however:
> > Package nginx-abi-1.24.0-1 is not installed.
> > Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> > dpkg: error processing package libnginx-mod-http-geoip (--configure):
> > dependency problems - leaving unconfigured
> > No apport report written because MaxReports is reached already
> > dpkg: dependency problems prevent configuration of libnginx-mod-http-brotli-filter:
> > libnginx-mod-http-brotli-filter depends on nginx-abi-1.24.0-1; however:
> > Package nginx-abi-1.24.0-1 is not installed.
> > Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> > dpkg: error processing package libnginx-mod-http-brotli-filter (--configure):
> > dependency problems - leaving unconfigured
> > No apport report written because MaxReports is reached already
> > dpkg: dependency problems prevent configuration of libnginx-mod-brotli:
> > libnginx-mod-brotli depends on libnginx-mod-http-brotli-filter; however:
> > Package libnginx-mod-http-brotli-filter is not configured yet.
> > dpkg: error processing package libnginx-mod-brotli (--configure):
> > dependency problems - leaving unconfigured
> > No apport report written because MaxReports is reached already
> > dpkg: dependency problems prevent configuration of nginx-core:
> > nginx-core depends on libnginx-mod-http-geoip (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
> > Package libnginx-mod-http-geoip is not configured yet.
> > nginx-core depends on libnginx-mod-http-geoip (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
> > Package libnginx-mod-http-geoip is not configured yet.
> > nginx-core depends on libnginx-mod-http-image-filter (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
> > Package libnginx-mod-http-image-filter is not configured yet.
> > nginx-core depends on libnginx-mod-http-image-filter (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
> > Package libnginx-mod-http-image-filter is not configured yet.
> > nginx-core depends on libnginx-mod-http-xslt-filter (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
> > Package libnginx-mod-http-xslt-filter is not configured yet.
> > nginx-core depends on libnginx-mod-http-xslt-filter (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
> > No apport report written because MaxReports is reached already
> > Package libnginx-mod-http-xslt-filter is not configured yet.
> > nginx-core depends on libnginx-mod-stream (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
> > Package libnginx-mod-stream is not configured yet.
> > nginx-core depends on libnginx-mod-stream (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
> > Package libnginx-mod-stream is not configured yet.
> > nginx-core depends on libnginx-mod-stream-geoip (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
> > Package libnginx-mod-stream-geoip is not configured yet.
> > nginx-core depends on libnginx-mod-stream-geoip (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
> > Package libnginx-mod-stream-geoip is not configured yet.
> > nginx-core depends on nginx (>= 1.25.4-3+ubuntu22.04.1+deb.sury.org+1); however:
> > Package nginx is not configured yet.
> > nginx-core depends on nginx (<< 1.25.4-3+ubuntu22.04.1+deb.sury.org+1.1~); however:
> > Package nginx is not configured yet.
> > dpkg: error processing package nginx-core (--configure):
> > dependency problems - leaving unconfigured
> > dpkg: dependency problems prevent configuration of libnginx-mod-mail:
> > libnginx-mod-mail depends on nginx-abi-1.24.0-1; however:
> > Package nginx-abi-1.24.0-1 is not installed.
> > Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> > dpkg: error processing package libnginx-mod-mail (--configure):
> > dependency problems - leaving unconfigured
> > No apport report written because MaxReports is reached already
> > dpkg: dependency problems prevent configuration of libnginx-mod-http-brotli-static:
> > libnginx-mod-http-brotli-static depends on nginx-abi-1.24.0-1; however:
> > Package nginx-abi-1.24.0-1 is not installed.
> > Package nginx which provides nginx-abi-1.24.0-1 is not configured yet.
> > dpkg: error processing package libnginx-mod-http-brotli-static (--configure):
> > dependency problems - leaving unconfigured
> > No apport report written because MaxReports is reached already
> > Setting up linux-modules-extra-5.15.0-101-generic (5.15.0-101.111) ...
> > Setting up linux-modules-5.15.0-101-generic (5.15.0-101.111) ...
> > Setting up linux-image-generic (5.15.0.101.98) ...
> > Setting up linux-generic (5.15.0.101.98) ...
> > Processing triggers for libc-bin (2.35-0ubuntu3.6) ...
> > Processing triggers for ufw (0.36.1-4ubuntu0.1) ...
> > Processing triggers for man-db (2.10.2-1) ...
> > Processing triggers for php8.3-cli (8.3.4-1+ubuntu22.04.1+deb.sury.org+1) ...
> > Processing triggers for php8.3-fpm (8.3.4-1+ubuntu22.04.1+deb.sury.org+1) ...
> > Processing triggers for linux-image-5.15.0-101-generic (5.15.0-101.111) ...
> > /etc/kernel/postinst.d/initramfs-tools:
> > update-initramfs: Generating /boot/initrd.img-5.15.0-101-generic
> > I: The initramfs will attempt to resume from /dev/nvme1n1p3
> > I: (UUID=1551ae32-6c68-4425-ae6f-32e60dbb2404)
> > I: Set the RESUME variable to override this.
> > /etc/kernel/postinst.d/zz-update-grub:
> > Sourcing file `/etc/default/grub' Sourcing file `/etc/default/grub.d/init-select.cfg'
> > Generating grub configuration file ...
> > Found linux image: /boot/vmlinuz-5.15.0-101-generic
> > Found initrd image: /boot/initrd.img-5.15.0-101-generic
> > Found linux image: /boot/vmlinuz-5.15.0-100-generic
> > Found initrd image: /boot/initrd.img-5.15.0-100-generic
> > Found linux image: /boot/vmlinuz-5.15.0-78-generic
> > Found initrd image: /boot/initrd.img-5.15.0-78-generic
> > Warning: os-prober will not be executed to detect other bootable partitions.
> > Systems on them will not be added to the GRUB boot configuration.
> > Check GRUB_DISABLE_OS_PROBER documentation entry.
> > Adding boot menu entry for UEFI Firmware Settings ...
> > done
> > Errors were encountered while processing:
> > nginx
> > libnginx-mod-http-image-filter
> > libnginx-mod-stream
> > libnginx-mod-ssl-ct
> > nginx-common
> > libnginx-mod-stream-geoip
> > libnginx-mod-http-xslt-filter
> > libnginx-mod-http-geoip
> > libnginx-mod-http-brotli-filter
> > libnginx-mod-brotli
> > nginx-core
> > libnginx-mod-mail
> > libnginx-mod-http-brotli-static
> > needrestart is being skipped since dpkg has failed
> > E: Sub-process /usr/bin/dpkg returned an error code (1)

yep got the same issue in nearly all of my 30 servers that I maintain. A big pain in the ass.

**Comment by ghbob** [comment]
@oerdnj any guidance on what the right steps are for a successful upgrade to avoid downtime? thank you!

**Comment by oerdnj** [comment]
> @oerdnj any guidance on what the right steps are for a successful upgrade to avoid downtime? thank you!

Well, the problem is that I still don't know what is causing the `nginx` to restart in the middle of the upgrade process. The Debian packager made changes to the packaging which on one hand simplified the external module building, but on the other hand - you see the result yourself.

I would suggest to upgrade rest of the system first and then upgrade all the `nginx-*` and `libnginx-mod-*` packages in a separate step.

As an alternative - what might work - would be to do:

```
systemctl stop nginx
systemctl disable nginx
apt upgradfe
systemctl enable nginx
systemctl start nginx
```

But I haven't tested this myself and it might or might not work.

**Comment by michaelk83** [comment]
> @oerdnj any guidance on what the right steps are for a successful upgrade to avoid downtime? thank you!

I'm not a sys-admin, but for people running servers, I would suggest to switch to Docker or Podman. This takes some more setup up front, but will let you:

A. Separate your NginX installation from the rest of the system. So you can upgrade them independently.
B. Upgrade the NginX image independently of the running container. Then you restart the container from the new image with practically no downtime. If there are problems with the upgrade, the container is still running with the previous version.
C. Since each image is built from scratch, you get a fresh installation each time, and avoid the upgrade issues mentioned here.

You can either use the official NginX image from DockerHub, or if you want to use this repository, you can build an image off a Debian base.

**Comment by ryankopf** [comment]
This was ridiculous.

Here's what I had to do:

First, backup ALL the custom configuration, such as anything in /etc/nginx/sites-available/*
```
sudo apt-get purge nginx nginx-common nginx-extras libnginx-mod* -y
sudo apt-get autoremove -y
sudo apt-get install -f
sudo apt-get update
sudo rm /lib/systemd/system/nginx.service
sudo rm /etc/systemd/system/nginx.service
sudo systemctl daemon-reload
```

THEN it would NOT work until I did a system reboot after too. For some reason, a resource gets locked during this process that doesn't come unlocked.

And then

```
sudo apt-get install nginx-extras libnginx-mod-brotli
```

**Comment by ghbob** [comment]
> As an alternative - what might work - would be to do:
> 
> ```
> systemctl stop nginx
> systemctl disable nginx
> apt upgrade
> systemctl enable nginx
> systemctl start nginx
> ```


Thanks, I think that just helped me get over the upgrade on another server without any issues.


Still confused about the autoremoval afterwards, it seems to have replace `nginx-core` or `nginx-full` with `nginx-common` and wants to remove anything not related? (honestly just guessing)
Which I guess is fine, if I don't use any of them.

```bash
nginx/focal,now 1.27.1-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed]
nginx-common/focal,now 1.27.1-1+ubuntu20.04.1+deb.sury.org+1 all [installed,automatic]
```

```bash
The following packages will be REMOVED:
geoip-database libgeoip1 libnginx-mod-http-auth-pam libnginx-mod-http-dav-ext libnginx-mod-http-echo libnginx-mod-http-geoip libnginx-mod-http-geoip2
libnginx-mod-http-image-filter libnginx-mod-http-subs-filter libnginx-mod-http-upstream-fair libnginx-mod-http-xslt-filter libnginx-mod-mail libnginx-mod-ssl-ct
libnginx-mod-stream libnginx-mod-stream-geoip libnginx-mod-stream-geoip2 nginx-core nginx-full
```

**Comment by thiagomeest** [comment]
> > @oerdnj any guidance on what the right steps are for a successful upgrade to avoid downtime? thank you!
> 
> Well, the problem is that I still don't know what is causing the `nginx` to restart in the middle of the upgrade process. The Debian packager made changes to the packaging which on one hand simplified the external module building, but on the other hand - you see the result yourself.
> 
> I would suggest to upgrade rest of the system first and then upgrade all the `nginx-*` and `libnginx-mod-*` packages in a separate step.
> 
> As an alternative - what might work - would be to do:
> 
> ```
> systemctl stop nginx
> systemctl disable nginx
> apt upgradfe
> systemctl enable nginx
> systemctl start nginx
> ```
> 
> But I haven't tested this myself and it might or might not work.

For me.. The only way that worked was run `apt --fix-broken install` before start nginx again.

Thanlks!!
