### ISSUE TITLE
Openssl encrypt fails

### ISSUE THREAD

**Issue by segadora** [oerdnj/deb.sury.org#555]
The latest patch seems to have broken openssl in php56

Package: php56

```
<?php
$iv = '1234567812345678';
var_dump(openssl_encrypt(serialize('foobar'), 'AES-256-CBC', 'base64:PNjgjy9o893RlP+z1/3iNZlCYgDmU3wXaChqbOYCVDc=', 0, $iv));
```

Returns on local environment:

```
string(24) "nv3muJeU8u+EgAqtzePutA=="
```

On CircleCi running the latest build it returns false.

No errors from PHP

**Comment by oerdnj** [comment]
@segadora Is that Ubuntu or Debian? And can you do `apt-cache policy libssl1.0 libssl1.1` and paste output here?

@zsalab Can you take a look?

**Comment by zsalab** [comment]
I gonna check out soon as possible

**Comment by zsalab** [comment]
**jessie non patched (libssl 1.0)**
php /tmp/ssltest.php 
string(24) "nv3muJeU8u+EgAqtzePutA=="

ldd /usr/bin/php5 |grep libssl
	libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x000003888ed8e000)

**stretch patched (libssl 1.1)**
 php /tmp/ssltest.php 
string(24) "nv3muJeU8u+EgAqtzePutA=="

ldd /usr/bin/php5.6 | grep libssl
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x000003da2fd56000)

**Comment by segadora** [comment]
I think its ubuntu 14.04

**Comment by zsalab** [comment]
@oerdnj maybe you should not add this openssl related patch to the versions not build with libssl 1.1
I really would like to help but I do not have time to debug the patched version with libssl 1.0; Of course I'm willing to debug and fix with libssl 1.1

**Comment by wizzent** [comment]
Hi,
same problem here on Ubuntu 14.04.5 LTS

wiz@local:~$ apt-cache policy libssl1.0 libssl1.1
libssl1.0.0:
  Installed: 1.0.1f-1ubuntu2.22
  Candidate: 1.0.1f-1ubuntu2.22
  Version table:
 *** 1.0.1f-1ubuntu2.22 0
        500 http://ubuntu.mirror.serverloft.eu/ubuntu/ trusty-updates/main amd64 Packages
        500 http://ubuntu.mirror.serverloft.eu/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.1f-1ubuntu2 0
        500 http://ubuntu.mirror.serverloft.eu/ubuntu/ trusty/main amd64 Packages
libssl1.0.2:
  Installed: 1.0.2k-1+deb.sury.org~trusty+5
  Candidate: 1.0.2k-1+deb.sury.org~trusty+5
  Version table:
 *** 1.0.2k-1+deb.sury.org~trusty+5 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
libssl1.0.0-dbg:
  Installed: (none)
  Candidate: 1.0.1f-1ubuntu2.22
  Version table:
     1.0.1f-1ubuntu2.22 0
        500 http://ubuntu.mirror.serverloft.eu/ubuntu/ trusty-updates/main amd64 Packages
        500 http://ubuntu.mirror.serverloft.eu/ubuntu/ trusty-security/main amd64 Packages
     1.0.1f-1ubuntu2 0
        500 http://ubuntu.mirror.serverloft.eu/ubuntu/ trusty/main amd64 Packages
libssl1.0.2-dbg:
  Installed: (none)
  Candidate: 1.0.2k-1+deb.sury.org~trusty+5
  Version table:
     1.0.2k-1+deb.sury.org~trusty+5 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
N: Unable to locate package libssl1.1
N: Couldn't find any package by regex 'libssl1.1'


The problem seems to be on the IV parameter, removing it it works (with the warning for empty IV)

**Comment by troelskn** [comment]
Output from apt-get policy below:

```
ubuntu@box100:~$ apt-cache policy libssl1.0 libssl1.1
libssl1.0.0:
  Installed: 1.0.1f-1ubuntu2.21
  Candidate: 1.0.1f-1ubuntu2.22
  Version table:
     1.0.1f-1ubuntu2.22 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
 *** 1.0.1f-1ubuntu2.21 0
        100 /var/lib/dpkg/status
     1.0.1f-1ubuntu2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
libssl1.0.2:
  Installed: 1.0.2k-1+deb.sury.org~trusty+5
  Candidate: 1.0.2k-1+deb.sury.org~trusty+5
  Version table:
 *** 1.0.2k-1+deb.sury.org~trusty+5 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
libssl1.0.0-dbg:
  Installed: (none)
  Candidate: 1.0.1f-1ubuntu2.22
  Version table:
     1.0.1f-1ubuntu2.22 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     1.0.1f-1ubuntu2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
libssl1.0.2-dbg:
  Installed: (none)
  Candidate: 1.0.2k-1+deb.sury.org~trusty+5
  Version table:
     1.0.2k-1+deb.sury.org~trusty+5 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
N: Unable to locate package libssl1.1
N: Couldn't find any package by regex 'libssl1.1'

```

**Comment by troelskn** [comment]
I can verify that passing NULL for `$iv` gives a useful output and a warning.

**Comment by zsalab** [comment]
I've reviewed the original patch and I found a bug related to the IV handling
Please try this patch (same URL but updated content):
https://zettasystem.com/0053-z-libssl-1.1-compatibility.patch

**Comment by segadora** [comment]
@wizzent are you able to test?

I am unsure how to apply the patch

**Comment by zsalab** [comment]
apt-get source php5.6
you will find a php-5.6.30 folder, and inside a debian/patches folder.... you should find a patch at the end which name similar like the URL before (please re download the patch and be sure no cached version), after that you're read to recompile (dpkg-buildpackage -us -uc -sa)

md5sum zettasystem.com/0053-z-libssl-1.1-compatibility.patch
b59e4d9189f1e1f6ee5e6e102fa5e1ce  zettasystem.com/0053-z-libssl-1.1-compatibility.patch

**Comment by wizzent** [comment]
Working on it now, sorry was busy on another task
Give me 15 minutes

**Comment by DivineOmega** [comment]
I'm receiving the following `EncryptException` in Laravel 5.1 based projects after the most recent upgrade to PHP 5.6 packages today. I assume this is related?

Screenshot: https://i.imgur.com/D50icAL.png

**Comment by zsalab** [comment]
@DivineOmega you mean, after patching with the new patch? Which Debian/Ubuntu version, what openssl linked to PHP engine?

**Comment by DivineOmega** [comment]
@zsalab Sorry, this is just the binaries from the PPA. I'm on Ubuntu 16.04 LTS. What details do you require regarding OpenSSL?

**Comment by oerdnj** [comment]
Uploaded `php5.6_5.6.30-4+deb.sury.org~*+1` with the new patch. Thanks.

**Comment by troelskn** [comment]
@DivineOmega yes, same issue.

**Comment by segadora** [comment]
@oerdnj the problem seems resolved with the latest build

**Comment by segadora** [comment]
The problem is resolved.

**Comment by oerdnj** [comment]
Thanks for confirmation. And @zsalab, thanks for quick fix.

**Comment by zsalab** [comment]
Thank you, I hope no more problems with the patch but please let me know if you have any further issues. I did the best what I could but it was 6500 lines code what I had to review and merge from PHP 7.1 and do not break the API in the 5.6.
Take my apologies because of the inconvenient hours for the users. I hope soon more and more going to be happy by the time they will have use PHP 5.6 in newer linux systems too (until end of the lifecycle of 5.6 series)

**Comment by wizzent** [comment]
It works also from here
Thanks

**Comment by wizzent** [comment]
Sorry, there is still a problem affecting the openssl_decrypt function.
Using AES256 it happens only when the text is longher than 16 characters (it could be a different limit on different cipher methods - I have not tested).
Seeing the result of the tests, it seems just a minor bug when the resulting string is composed.
Consider this code:

<?php
$SSL_IV = "4887546896548512";
$SSL_KEY = "gf6879uh2efh8wyfg9uewgf78wufh9whf9wuhwiuvhwiu";

$plain = $_SERVER["argv"][1];
$enc = openssl_encrypt($plain, "AES256", $SSL_KEY, 0, $SSL_IV);
$dec = openssl_decrypt($enc, "AES256", $SSL_KEY, 0, $SSL_IV);

var_dump($plain);
var_dump($enc);
var_dump($dec);
?>

Using different values for $plain:

(up to 16 characters - Correct)
$ php xxx.php 0123456789ABCDEF
string(16) "0123456789ABCDEF"
string(44) "bENRlpIGWuwr8Dcr6JGsAMX+HN03lM3dtrkICOIPYlA="
string(16) "0123456789ABCDEF"

(17 characters - Error)
php xxx.php 0123456789ABCDEFG
string(17) "0123456789ABCDEFG"
string(44) "bENRlpIGWuwr8Dcr6JGsABTJ/EjJ9VtceC7ZhIcDBv4="
string(17) "G123456789ABCDEFG"

(even more characters - Error)
$ php xxx.php 0123456789ABCDEFGHIJKLMNOPQRS
string(29) "0123456789ABCDEFGHIJKLMNOPQRS"
string(44) "bENRlpIGWuwr8Dcr6JGsAKDz9TdPKcTfweZ8oQtKDqk="
string(29) "GHIJKLMNOPQRSDEFGHIJKLMNOPQRS"


It seems the blocks are not handled correctly.

Bye

**Comment by zsalab** [comment]
@wizzent can you please provide the source of the xxx.php - I'm not sure what we talking about

**Comment by wizzent** [comment]
Oh sorry, the code has been removed from the post.
Here it is the source code:

$SSL_IV = "4887546896548512";
$SSL_KEY = "gf6879uh2efh8wyfg9uewgf78wufh9whf9wuhwiuvhwiu";
$plain = $_SERVER["argv"][1];
$enc = openssl_encrypt($plain, "AES256", $SSL_KEY, 0, $SSL_IV);
$dec = openssl_decrypt($enc, "AES256", $SSL_KEY, 0, $SSL_IV);
var_dump($plain);
var_dump($enc);
var_dump($dec);

**Comment by zsalab** [comment]
I've started a new build, I'm not sure this will fix, but I hope so.... I will provide the patch here if looks fixed

**Comment by wizzent** [comment]
Once available I'll test and let you know!
Thanks!

**Comment by zsalab** [comment]
Sorry, looks does not help, I have to find the bug It will take some time

**Comment by segadora** [comment]
@zsalab are the build broken again ?

**Comment by zsalab** [comment]
Yes, the same issue, I have a good guess where is the problem, but it will take time to modify the patch , build and test it.

**Comment by oerdnj** [comment]
I have replaces the code in `ext/openssl/openssl.c` with:
```
#if OPENSSL_VERSION_NUMBER < 0x10100000L
#include "openssl.c.1.0
#else
#include "openssl.c.1.1
#endif
```
for the time being. If @zsalab (or anybody) else could restore the functionality with OpenSSL 1.0, I would very much like to have just one version of `openssl.c` (for my sanity reasons).

**Comment by DivineOmega** [comment]
For reference, and to help others find this issue, this is the error message I'm receiving in Laravel projects currently (with the latest PHP 5.6 PPA packages (Ubuntu 16.04 LTS)).

```
ErrorException in Encrypter.php line 107:
unserialize(): Error at offset 0 of 70 bytes
```

Thanks for everyone's quick work on this. :)

**Comment by troelskn** [comment]
For anyone having acute need to get Laravel to run on this version, I made a workaround: https://gist.github.com/troelskn/b2502a84a5f6a1f0332d5b6bb33471a5

**Comment by oerdnj** [comment]
So, in `5.6.30-5*` the ext/openssl/openssl.c code is using the original PHP code when compiled with OpenSSL 1.0 and the @zsalab patched code when compiled with OpenSSL 1.1.

Sorry all for all the troubles.

```
root@lettie:/tmp# php test.php 0123456789ABCDEF
string(16) "0123456789ABCDEF"
string(44) "bENRlpIGWuwr8Dcr6JGsAMX+HN03lM3dtrkICOIPYlA="
string(16) "0123456789ABCDEF"
root@lettie:/tmp# php test.php 0123456789ABCDEFG
string(17) "0123456789ABCDEFG"
string(44) "bENRlpIGWuwr8Dcr6JGsABTJ/EjJ9VtceC7ZhIcDBv4="
string(17) "0123456789ABCDEFG"
root@lettie:/tmp# php test.php 0123456789ABCDEFGHIJKLMNOPQRS
string(29) "0123456789ABCDEFGHIJKLMNOPQRS"
string(44) "bENRlpIGWuwr8Dcr6JGsAKDz9TdPKcTfweZ8oQtKDqk="
string(29) "0123456789ABCDEFGHIJKLMNOPQRS"
```

**Comment by DivineOmega** [comment]
@troelskn Thanks for the work around. I'm sure you're aware, but for sake of else seeing this, because this workaround removes the initialization vector (IV), it does weaken the encryption. Therefore, it should not be used in production, only as a temporary workaround on development environments.

**Comment by troelskn** [comment]
@DivineOmega Absolutely - good thing that you point it out.

**Comment by zsalab** [comment]
Please do not use the patch until I'm sure no other complications... I'm building a new version and I will test much as I can.... I don't want to provide the patch unless I know no more bugs
Sorry, I'm try to fix soon as possible

**Comment by DivineOmega** [comment]
Just to confirm, the latest package updates appear to have resolved my issues.
